### ISSUE TITLE
Enable Github's Discussions

### ISSUE THREAD

**Issue by filip26** [alps-io/spec#101]
Hi,
I'm just thinking it would be great to try Github's discussions for this repository.  It looks better suited for discussing stuff than Issues.

[Join the conversation with GitHub Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions)

It's available for all my public repos so I hope you can enable it in settings here as well. Happy to help.

**Comment by mamund** [comment]
@filip26 

great idea! i've opened up the discussions tab for the spec repo now.

-- thanks.
