### ISSUE TITLE
Conditions for adding `rel` tag

### ISSUE THREAD

**Issue by koriym** [alps-io/spec#111]
In the diagram below, all the transitions towards Blog are `rel=collection`, but

A) Should I give `rel=collection` only to `BlogPosting => Blog`, which is essentially an `item => collection` relationship?

B) Or should I always give `rel=collection` when linking to a `collection` type resource no matter where the link from?

![image](https://user-images.githubusercontent.com/529021/116328480-11637b80-a804-11eb-83fe-fcdfb684123d.png)

Code:
```
 {"id": "goBlog", "type": "safe", "rt": "#Blog", "rel": "collection"},
```

If the answer is B, it is simple, but if the answer is A, ALPS needs to distinguish between the two IDs?

**Comment by koriym** [comment]
Ok. The answer is "B", right?

**Comment by mamund** [comment]
yes. that's what i do

**Comment by koriym** [comment]
Arigato.
