### ISSUE TITLE
Markdown would be very nice

### ISSUE THREAD

**Issue by fosdev** [alps-io/spec#24]
https://github.com/alps-io/spec/blob/master/draft-00.txt#L593-L597

**Comment by Xophmeister** [comment]
Another vote for markdown from me. Although, of course, there's the perennial issue of what exactly that means, given its loose spec and multiple/vendor-specific definitions. My view is that should be left unto the client to worry about!

Is there any reason why both AsciiDoc *and* Markdown can't be supported by the ALPS spec? Why the "one or the other" attitude, besides brevity's sake?

**Comment by mamund** [comment]
i added asciidoc *because* it offers the same benefits of markdown w/o the
difficulty of sorting out vendor politics ;)

if we *do* add support for MD, i'd want to use this I-D as a guide
(including the indication of "variants" to help sort our implementations)
https://tools.ietf.org/html/draft-ietf-appsawg-text-markdown-05

comments?




mamund
+1.859.757.1449
skype: mca.amundsen
http://amundsen.com/blog/
http://twitter.com/mamund
https://github.com/mamund
http://linkedin.com/in/mamund

**Comment by Xophmeister** [comment]
Given the holy war and schism that was sparked the last time a standardisation attempt was made, this I-D seems like a sensible and pragmatic approach. So, yes: Sounds like a plan!

**Comment by mamund** [comment]
cool. do you want to whip up a PR that adds MAY support for markdown based
on this I-D? ​

**Comment by fosrias** [comment]
So, there is some controversy in play ATM on markdown per the following:

* https://twitter.com/markdown/status/507341395137658880
* http://blog.codinghorror.com/standard-markdown-is-now-common-markdown/

Apparently John Gruber, author of Markdown has a problem with the aforementioned spec and use of Markdown. CommonMark, I believe, is what is making its way toward a spec. So, not sure how all this affects the proposed RFC.

**Comment by Xophmeister** [comment]
The I-D mentioned by @mamund side-steps this issue by not imposing any spec (there's nary a Backus-Naur to be seen), but rather deferring to the client to parse, using a `variant` parameter on the media type as a "hint". In my opinion, it's actually quite careful not to rile Gruber -- his work is explicitly referenced as being standard -- and recommends an IANA registry for variants (e.g., CommonMark, GitHub Flavoured, etc.)

**Comment by fosrias** [comment]
Ok. Did not read the spec close enough. :thumbsup: from me @mamund.
