### ISSUE TITLE
Misc. Typos, Etc.

### ISSUE THREAD

**Issue by fosdev** [alps-io/spec#25]
* For' 
https://github.com/alps-io/spec/blob/master/draft-00.txt#L189

* Unnecessary whitespace
https://github.com/alps-io/spec/blob/master/draft-00.txt#L320

* This is not a sentence:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L399-L400

* … child of a ‘descriptor’ element.
https://github.com/alps-io/spec/blob/master/draft-00.txt#L610

I can see how you have worded this consistently for example with:

https://github.com/alps-io/spec/blob/master/draft-00.txt#L626

but they feel a little awkward when you read it (you think in xmlese, average Joe may not). Can ignore this one if so inclined.

* calues => values
https://github.com/alps-io/spec/blob/master/draft-00.txt#L721

* imo this is hard to read. I would recommend putting the tags on a separate line here: 
https://github.com/alps-io/spec/blob/master/draft-00.txt#L767-L771

also, you have name=q vs. class=q in the button tag here:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L811

* name should be in quotes for consistency:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L794

Ditto on ‘id’ here:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L796

* closing quote needed after semantic:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L811

* id and descriptor in quotes for consistency:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L913

* inconsistent use of media-type here. Just “media type” everywhere else:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L193

personally, I prefer media-type.

* Might be nice to put a reference in the footnotes to IRIs here: 
https://github.com/alps-io/spec/blob/master/draft-00.txt#L1244
and in application/alps+json profile parameter definition

Duerst, M. and M. Suignard, "Internationalized                   Resource Identifiers (IRIs)", RFC 3987, January 2005.

https://tools.ietf.org/html/rfc3987

**Comment by ApiSecRay** [comment]
Section 2.2.6 has the typo 'defintion'.

**Comment by ApiSecRay** [comment]
Section 3 has the typo '[details'.

**Comment by ApiSecRay** [comment]
Section A.1 has the typo 'represetentations'.

**Comment by mamund** [comment]
adding some items from Graham Klyne (from the media-type list):

Sect 1.4

"This URL SHOULD be assumed to be dereferencable." reads oddly (making a normative statement about an assumption?).

Maybe just "This URL SHOULD be dereferencable."?

---- 

Sect 2.2.2: missing {...} around "alps" content?

{ "alps : "doc" : { "value" : "..." }, ... }

(cf. sect 2.3.3.1)

**Comment by mamund** [comment]
@fosdev:

please review the misc items in this thread and highlight any that *remain* unresolved. due to updates, the line numbers no longer match up ;<.

i'll attack as many of these as i can this week to close this item out.

**Comment by mamund** [comment]
@fosdev: see typos branch for fixes from this list.

**Comment by mamund** [comment]
closed as completed.
