### ISSUE TITLE
HTML examples inconsistent and confusing:

### ISSUE THREAD

**Issue by fosdev** [alps-io/spec#27]
Is this correct? Shouldn't this be the "collection" ID has become the CSS class of an HTML form? Or do you actually want the class on the submit button. 
https://github.com/alps-io/spec/blob/master/draft-00.txt#L397-L398

You put the class on the search button, not the form here:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L800-L805

and again differently here:
https://github.com/alps-io/spehttps://github.com/alps-io/spec/issues/3#issuecomment-34900427c/blob/master/draft-00.txt#L976

See also: https://github.com/alps-io/spec/issues/3#issuecomment-34900427

Not sure if all this is on purpose, but seems that a transition descriptor in html should tie to a class on a form or a tag and a semantic descriptor to a class (or name) on an input attribute or something else. Regardless, think this needs to tighten up. Maybe it is on purpose that all this can be different, but seems you should be more opinionated for clarity for others trying to grok this all the first time.

**Comment by fosrias** [comment]
Closed per comment on issue #22
