### ISSUE TITLE
Alps serialization - 'type' is a reserved keyword 

### ISSUE THREAD

**Issue by junosw** [alps-io/spec#29]
Many languages today have libraries for serializing JSON to objects that can be used in code and back to JSON.  One of the common patterns used is to write classes whose properties are then serialized to JSON where the property name would be the key in a typical JSON key/value pair.

Making use of these serialization libraries presents a problem when implementing serializers for ALPS because of the word 'type' that is used in the format.  'type' is a keyword in many languages and thus cannot be a property name of a class, breaking the use of serialization libraries that use the pattern described above.

I am facing this issue today and do not have a choice other than to either find a workaround to my serialization libraries or simply not follow the format (and use "type_" or something like that)

**Comment by mamund** [comment]
ok @fosrias and @junosw 

time to clear this up!

right now anything other than "`type` is going to be a breaking change. i'd like to avoid that and close this out.

any objections?

**Comment by fosrias** [comment]
@mamund was wondering about that. At this point I think we close this and leave it to ALPS client developers to accommodate this using some other convention. So, :+1: to close by me.

**Comment by mamund** [comment]
agreed.

closed w/o actoin.
