### ISSUE TITLE
Appending doc value vs. replacing when extending descriptor

### ISSUE THREAD

**Issue by fosdev** [alps-io/spec#30]
If I href some descriptor, the spec currently indicates that any attributes/elements in the inheriting descriptor override the base descriptor. In the case of a doc element, it may be desireable to append/decorate the base value vs. completely replace it.

**Comment by fosrias** [comment]
@mamund We have never discussed this. Don't feel strongly about it reading it now. I think the documentation of the present descriptor is king, so I vote to just close this. Shall I?

**Comment by mamund** [comment]
closed w/o action.
