### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by fosdev** [alps-io/spec#36]
Develop wording for extension of ALPS for other uses as a base spec and refine/find other ways to extend profiles at runtime.

**Comment by fosrias** [comment]
Related to: https://github.com/alps-io/spec/issues/17 and https://github.com/alps-io/spec/issues/7. Should we collapse all these @mamund?

**Comment by mamund** [comment]
Sure. Pick one and do it.

**Comment by fosrias** [comment]
@mamund Closing his one. Will leave other two open as on further review they address separate issues.
