### ISSUE TITLE
clarifying href with fragment to local descriptor

### ISSUE THREAD

**Issue by fosrias** [alps-io/spec#56]
Currently, href requires a resolvable URL in the spec but indicates fragments can be used in section [2.2.7.2](http://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-00#section-2.2.7.2). The example there shows a fragment in a fully qualified URL. I think we want to allow and should clarify that  using a fragment in an href to indicates a relative URL pointing to a descriptor in the document. This is not clear in the specs ATM IMO,. That is, we should support and make clear:

```
<descriptor id="first_name"/>
<descriptor id="last_name"/>
<descriptor id="person">
  <descriptor href="#first_name/>
  <descriptor href="#last_name/>
</descriptor>
```

**Comment by mamund** [comment]
yep. good point.
