### ISSUE TITLE
Is there a need for a protocol related section or separate spec w/r to types and uniform interface verbs

### ISSUE THREAD

**Issue by fosrias** [alps-io/spec#58]
I wonder if we should at least put SHOULD wording in the spec w/r to HTTP or consider another doc like media-type mappings. One cannot rely on verbs given implementors can do wonky things. One reason a profile is necessary is you cannot rely on a protocol uniform interface verb to dictate safe and unsafe reliably. But a profile should reliably state that and possibly constrain verbs allowed to be used with that type per a particular protocol. Makes the ALPS profile have greater weight for understanding APIs I think.

**Comment by fosrias** [comment]
I think this is a different spec for sure. I wonder if there is a general approach to mapping that you could have a spec that indicates how to map ALPS to media-types or protocols? Might be over ambitious, but I think in the context of ALPS ATM there is no need for this. In the context of DISCO and services implementing profiles, probably.

**Comment by fosrias** [comment]
And maybe we should close this and open an issue on a repo for spec around mappings and keep mapping spec related issues there. We can keep mapping wording clarification issues here. But I think we should not discuss here.

**Comment by mamund** [comment]
Done. 

Feel free to start another repo for mapping/binding efforts.
