### ISSUE TITLE
Use of <xref>with content</xref> has incorrect syntax.

### ISSUE THREAD

**Issue by fosrias** [alps-io/spec#63]
Per [RFC2629] (https://tools.ietf.org/html/rfc2629#section-2.3.1.4), putting content in an xref element results in generating an extra <cite/> element that shows up in html as [something]. Thus, in our current spec, the html version has thinks like ['descriptor'](#) [prop-descriptor] all over. 

The way to fix this is not to use content, but rather format="title" in the <xref/> tag per [xml2rfc FAQS Section 3.11](http://xml2rfc.ietf.org/xml2rfcFAQ.html#anchor19).

So for example we need to change throught the document things like:

```xml
 <xref target="prop-descriptor">'descriptor'</xref>
```

to

```xml
 <xref target="prop-descriptor" format="title"/>
```

**Comment by mamund** [comment]
Right. Good catch.
