### ISSUE TITLE
add ref to frag ids in media type definitions

### ISSUE THREAD

**Issue by mamund** [alps-io/spec#65]
Section 4.

I think the media type registrations should reference the fragment id interpretation (sect 2.2.7.2).

/via Graham Klyne

**Comment by mamund** [comment]
add ref to JSON Pointer RFC6901 sec6 for frag ids in JSON flavors of ALPS:
http://tools.ietf.org/html/rfc6901#section-6

add ref to XPtrFramework and Shorthand pointers for fragids in XML flavors of ALPS
http://www.w3.org/TR/xptr-framework/#shorthand

**Comment by mamund** [comment]
@fosrias 

in reviewing the various options for frag-id support, i've looked at JSON Pointer and XPointer as well as guidance on "best practices for implementing/supporting frag ids. while pointers are available (JSONPointer, XPointer) i propose to use only "Plain Name" frag-ids for ALPS[1]. basically, just an opaque string (e.g. `"#user"` -> `id="user"`) and _not_ any pointer schemes. 

sound ok?

[1] http://www.w3.org/TR/fragid-best-practices/#reserve-plain-name-fragids

**Comment by fosrias** [comment]
Yeah. That has been my understanding from the beginning. Further, I am not
sure w/r to alps there would be any point to pointing to some isolated part
of a descriptor. href is sufficient to point to a specific descriptor.

So, short answer: concur

**Comment by mamund** [comment]
there might be a call from some to *also* support the pointer specs. language/guidance is fuzzy there (as in, we're supposed to support the specs already established for the "suffix" media types). 

i'll leave it like this and let's see how it goes.

**Comment by mamund** [comment]
closed per pr #72
