### ISSUE TITLE
clarify the use of the term "semantic"

### ISSUE THREAD

**Issue by mamund** [alps-io/spec#66]
Section 2.2.12

I'm not understanding what you mean by the description of type="semantic".  The examples given (html.span and html.input) aren't helping in this respect.

My guess is that some kind of introduction to the kind of hypermedia model your basing this upon is needed.  I think there's a lot of tacit knowledge permeating the spec that needs to be surfaced for those who aren't in tune with your approach.

/via Graham Klyne

**Comment by fosrias** [comment]
@mamund I really think this would be better served to use something like a JSON property or and xml tag(or attribute?). HTML is too far removed.

**Comment by mamund** [comment]
you mean in the example cases in the spec doc? 

when mapping a profile onto HTML, we still need to use some element, right? and `span` and `input` are proper examples of mapping "semantic" descriptors, right?

**Comment by fosrias** [comment]
Yeah. I think that is fine, but it is far more abstract than some example of showing a semantic descriptor being a json property on JSON or some equivalent in xml. Could leave in the HTML, but may the semantic section warrants some code examples for clarity.

**Comment by mamund** [comment]
maybe we need an additional section up near the top, too.
