### ISSUE TITLE
Text cleanups

### ISSUE THREAD

**Issue by rickardoberg** [alps-io/spec#82]
As per my email to the mailing list, here are some issues I found in the current spec that could use some cleanup:
* 2.2.2 "doc" has the following JSON example:

JSON:  { "doc" : { "format" : "text" : "value" : "Date of Birth ..."  } }
Is the semicolon between text and value a typo?

* 2.2.2 "JSON: { "descriptor" : { { "doc" : { "value" : "..." } ... } }"
Is the double { a typo? The following seems more reasonable:
"JSON:  { "descriptor" : [ { "doc" : { "value" : "..." } ...  } ]"

* 2.2.2 "JSON: { "alps : "doc" : { "value" : "..." }, ... }"
Is this also a typo? The following seems more reasonable:
JSON:  { "alps : {"doc" : { "value" : "..." }}, ...  }

* 2.2.3 "One or more 'descriptor' elements SHOULD appear as children of 'alps'."
In the JSON serialization, is the "descriptor" element optional under
"alps", or must it be present as an empty array if no descriptors are
included?

* 2.2.3 states the "ext' may be an attribute of "descriptor", but then
2.2.4 describes "ext" as an element, and 2.3.3.1 examples shows it can
even be many of them. Which one is right?

* 2.2.4 "The 'id' property is REQUIRED" but then example in 2.3.3.1
shows ext without id property. Which one is right?

* 2.2.14 "If no value appears, then 'version="1.0"' is implied."
I'm assuming this should be "then '1.0' is implied"

* 2.3.3.1 In the example:
"description" : {"value" : "results format"}
I'm assuming this should be:
"doc" : {"value" : "results format"}

**Comment by mamund** [comment]
covered in pending draft-04

**Comment by mamund** [comment]
most of the clean ups completed in commit: 17dd302dd1a3a38aaa18c737f3cfeaa18b86147e
