### ISSUE TITLE
add TEXT property to DESCRIPTORS

### ISSUE THREAD

**Issue by mamund** [alps-io/spec#86]
instead of having to use the DOC nested element for any human-readable content, add a TEXT element to hold oneliners

```
<descriptor id="hatSize" type="semantic" text="indicates size of the hat" />
```

```
{"descriptor" : {"id" : "hatSize", "type" : "semantic", "text" : "indicated size of the hat" } }
```

**Comment by fosrias** [comment]
So, per some of the other options I discussed around `ext`, is there a reason to not reuse the term `doc` as an attribute here? Seems there are some cases where that would produce some nice syntactic sugar and the rule can be precedence for xml. This may require a little re-working of the `doc` wording.

Not sure the value of adding a new `text` element myself.

**Comment by mamund** [comment]
i'd prefer to not confuse long strethes of text (DOC) with quick single-string lines (TEXT).

the TEXT can be usesd as rollover content for element in HTML, prompts in some other formats. DOC can be used to product long-form documentation.

thoughts?

**Comment by mamund** [comment]
what about description or doc-text or *title*?
