### ISSUE TITLE
add TAGS property to all elements

### ISSUE THREAD

**Issue by mamund** [alps-io/spec#88]
add the TAGS element to DESCRIPTOR, LINK, DOC, EXT, and ALPS elements as a way to have "tag bucket" to add useful values to any element. this will make implementing reader/writers easier w/o requiring lots of additional document format approvals in the future. The value of the TAGS element is a space-separated list.

```xml
<alps version="1.0" tags="draft">
  <link href="http://example.org/profiles/help.html" tags="help-file" />
  <doc tags="abstract">
    Haberdashery vocabulary for hat stores with added features fo snocaps and hoodies.
  </doc>
  <descriptor id="hatSize" type="semantic" tags="property documentation">
    <ext id="sizeList" value="7, 8, 9, 10, 11, 12"  tags="enum documentation" />
</alps>
```
in the above example, the TAGS contain the following unique values: `draft`, `help-file`, `abstract`, `property`, `documentation`, `enum`

**Comment by filip26** [comment]
What is the relationship between `tags` and `rel`? 

All other attributes and elements use singular form, what about just `tag`?

**Comment by mamund** [comment]
let's clarify relation between TAG and REL

**Comment by mamund** [comment]
i wrote up a document to describe use of ID, NAME, REL, and TAG here:
https://github.com/alps-io/misc-docs/blob/master/id-name-rel-tag.asciidoc

if there are no objections, I'd like to add TAG to the spec (as OPTIONAL) and incorporate the doc guidance into the spec, too.

wdyt?
