### ISSUE TITLE
add SRC/REF/SAME property to DESCRIPTOR and EXT elements

### ISSUE THREAD

**Issue by mamund** [alps-io/spec#89]
NOTE: this is meant to help support a `sameAs` functionality within ALPS (see #12 )

the SRC (or REF? or SAME?) proprety is an optional property that you can use to reference the source or provenance of a DESCRIPTOR or EXT element.  For example, you can define a semantic element with the `id` property set to `"firstName"` and a `src` property set to  point to the source defintiion in schema.org (in this case `https://schema.org/givenName`).

```xml
<descriptor id="firstName" type="semantic" src="https://schema.org/givenName" />
```

**Comment by fosrias** [comment]
Can `src` be a url to an ALPS `descriptor` to show SameAs?

**Comment by mamund** [comment]
Probably. Would like to explore possible problems but if be happy if that could work.

I'll write up a first pass and we can discuss.

**Comment by mamund** [comment]
for this release, we'll be adding the `def` element to descriptors. the value of `def` will be an IRI that uniquely identifies the defintiion of the `descriptor`. Note that this might not be the equivalent of `sameAs` and we can address that separately.
