### ISSUE TITLE
Section 2.2.7 id section expansion

### ISSUE THREAD

**Issue by fosdev** [alps-io/spec#9]
I think there are enough significant ideas to warrant the following sections:

2.2.7.1 to discuss fragments in ALPS explicitly

2.2.7.2 Suggested to discuss definition of link relations:
https://github.com/alps-io/spec/blob/master/draft-00.txt#L801
This is a really important idea that should not be lost (missed) in here.

Also, I think this example is misleading in that I think it needs some profile name:  http://example.org/rel/purchased-by
https://github.com/alps-io/spec/blob/master/draft-00.txt#L803

**Comment by fosrias** [comment]
@mamund Should this be closed? Seems we have done this.

**Comment by mamund** [comment]
closed -- see #65 for follow up.
