### ISSUE TITLE
Use contentType and contentEncoding to specify doc element content and encoding

### ISSUE THREAD

**Issue by filip26** [alps-io/spec#91]
A motivation is to let a user choose any 'doc' content (including non-text).

e.g.
```xml
<doc contentType="application/xml" (contentEncoding="text")?><![CDATA[
...
]]></doc>
```

```javascript
"doc": {
   "contentType": "text/markdown",
   "contentEncoding": "text"
   "value": "...."
}
```

```javascript
"doc": {
  "contentType": "application/pdf",
  "contentEncoding": "base64",
  "value": "dG....VzdA=="
}
```

This change implicates deprecation of the 'format' on 'doc' element.

**Comment by mamund** [comment]
@filip26 

can you prepare some remarks for an upcoming AOOH to help us discuss/decide this one?

**Comment by mamund** [comment]
add `contentType` if value is not understood, assume `contentType="text/plain"`

we'll skipp `contentEncoding` for now

**Comment by mamund** [comment]
issue closed. 

start a new issue for `contentEncoding` if/when ready.
