### ISSUE TITLE
add REL property to DESCRIPTOR

### ISSUE THREAD

**Issue by koriym** [alps-io/spec#93]
Currently `REL` is restricted to use in `LINK`. 
https://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-03#section-2.2.10

**Comment by koriym** [comment]
I don't think so. But it should be limited to those that aren't `semantic`?

**Comment by mamund** [comment]
@koriym :

i don't think we need to worry about _preventing_ the use of `rel` on `type="semantic" `descriptors. there is no real danger and there _might_ be some benefit that someone can come up w/.
