### ISSUE TITLE
LINK element can be an array

### ISSUE THREAD

**Issue by mamund** [alps-io/spec#94]
per @koriym:

make sure the LINK element 2.8.8 can be an array, too.

**Comment by mamund** [comment]
per @filip26
make sure it can be both a single item OR an array.

**Comment by filip26** [comment]
It is not just a `link` element, but also `ext`, `doc`, `descriptor` ( in a case of ALPS+JSON and ALPS+YAML). To prevent having arrays of just one item and to improve readability, I would go with:

* an element can be represented as a single element
* an element can be represented as an array of single element  (no multidimensional arrays)

**Comment by mamund** [comment]
sounds good. i'll write it up and update this issue for review.  -- thanks.
