### ISSUE TITLE
create a public end-point for ALPS schemas

### ISSUE THREAD

**Issue by mamund** [alps-io/spec#98]
@koriym mentioned the need to have a public URL for our JSON and XSD schema documents for ALPS. @koriym brought up github.io and @smizell mentioned using netlify for this.

i'm adding this issue here to call out the need and help focus the discussion and encourage collboration to complete the task.

-- @mamund

**Comment by mamund** [comment]
I propose we start a new repo just for schemas to make it easier to manage and track changes.

can we just move the schemas folder from the spec repo and make it a new schema?

i'm looking for volunteers to manage the repo (@koriym? @smizell? others?)

wdyt?

**Comment by mamund** [comment]
schemas are now handled in a separate repo here: https://github.com/alps-io/schemas

and the current schemas are published here: https://alps-io.github.io/schemas/

thanks to @koriym and @smizell for this work

**Comment by koriym** [comment]
Congrats 🎉
